### ISSUE TITLE
epic: frontend refactor

### ISSUE THREAD

**Issue by falafeljan** [ununu-p2p/ink-desktop#86]
this is an epic issue that concerns a collection of major refactor and enhancements for the frontend:
- [ ] move tabbing management into app wrapper (#85)
  * current solution breaks with the next.js router
- [ ] use graphql for communication layer/API
  * self-documenting API
  * better separation between frontend and backend
- [ ] move from styled-components (SC) to CSS modules, SASS, etc.
  * SC tends to become cluttered for large components
  * SC doesn't always play well with next.js
  * SC requires more learning for the majority of developers
- [ ] establish more explicit, global state management
  * we don't use any explicit global state management, other than possibly react contexts
  * global state management should help with caching data instead of continuously polling the backend
